--- Cargo.toml.orig	2025-04-02 07:26:48 UTC
+++ Cargo.toml
@@ -21,5 +21,10 @@ bytemuck = "1"
 gimli = { version = "0.31.0", features = ["endian-reader"] }
 serde = { version = "1.0.197", features = ["derive"] }
 bytemuck = "1"
-pcode = { git = "https://github.com/icicle-emu/icicle-emu" }
+pcode2 = { git = "https://github.com/icicle-emu/icicle-emu", package = "pcode"}
 ahash = "0.8.11"
+
+[profile.release]
+opt-level = 2
+debug = false
+strip = "symbols"
