--- sleigh/sleigh-runtime/Cargo.toml.orig	2025-07-27 15:17:30 UTC
+++ sleigh/sleigh-runtime/Cargo.toml
@@ -1,6 +1,6 @@ name = "sleigh-runtime"
 [package]
 name = "sleigh-runtime"
-version = "0.1.0"
+version = "0.1.1"
 edition = "2021"
 
 [dependencies]
