--- sleigh/sleigh-parse/Cargo.toml.orig	2025-07-27 15:16:40 UTC
+++ sleigh/sleigh-parse/Cargo.toml
@@ -1,6 +1,6 @@ name = "sleigh-parse"
 [package]
 name = "sleigh-parse"
-version = "0.3.0"
+version = "0.3.1"
 edition = "2021"
 
 [dependencies]
