PORTNAME=       datovka
DISTVERSION=    4.21.0
CATEGORIES=     devel
MASTER_SITES=   https://secure.nic.cz/files/datove_schranky/${DISTVERSION}/

MAINTAINER=     freebsd@sysctl.cz
COMMENT=        Qt re-implementation of Datovka.
WWW=            https://gitlab.nic.cz/datovka/libdatovka

LICENSE=        LGPL3
LICENSE_FILE=   ${WRKSRC}/COPYING

USES=		qmake qt:5 tar:xz

.include <bsd.port.mk>
