# $FreeBSD$

PORTNAME=	libusb
PORTVERSION=	0.1.4
DISTVERSIONSUFFIX=	-3.el7
CATEGORIES=	devel linux

MAINTAINER=	emulation@FreeBSD.org
COMMENT=	This package provides a way for applications to access USB devices. (CentOS ${LINUX_DIST_VER})

USES=		linux:c7
USE_LDCONFIG=	yes
USE_LINUX_RPM=	yes

OPTIONS_DEFINE=	DOCS

.include <bsd.port.mk>
