--- chromium/third_party/ffmpeg/chromium/config/Chrome/freebsd/x64/libavutil/ffversion.h.orig	2022-06-07 19:28:37 UTC
+++ chromium/third_party/ffmpeg/chromium/config/Chrome/freebsd/x64/libavutil/ffversion.h
@@ -0,0 +1,5 @@
+/* Automatically generated by version.sh, do not manually edit! */
+#ifndef AVUTIL_FFVERSION_H
+#define AVUTIL_FFVERSION_H
+#define FFMPEG_VERSION "N-107578-gf6449ff8e6"
+#endif /* AVUTIL_FFVERSION_H */
