--- chromium/third_party/ffmpeg/chromium/config/Chrome/freebsd/x64/libavutil/avconfig.h.orig	2022-06-07 19:28:29 UTC
+++ chromium/third_party/ffmpeg/chromium/config/Chrome/freebsd/x64/libavutil/avconfig.h
@@ -0,0 +1,6 @@
+/* Generated by ffmpeg configure */
+#ifndef AVUTIL_AVCONFIG_H
+#define AVUTIL_AVCONFIG_H
+#define AV_HAVE_BIGENDIAN 0
+#define AV_HAVE_FAST_UNALIGNED 1
+#endif /* AVUTIL_AVCONFIG_H */
