PORTNAME=	box64
DISTVERSIONPREFIX=v
DISTVERSION=	0.3.4
CATEGORIES=	emulators

MAINTAINER=	freebsd@sysctl.cz
COMMENT=	Box64 - Linux Userspace x86_64 Emulator with a twist,\
		targeted at ARM64, RV64 and LoongArch Linux devices.

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		cmake
USE_GCC=	yes
USE_GITHUB=	yes
GH_ACCOUNT=	ptitSeb
GH_PROJECT=	box64

.include <bsd.port.mk>
