--- browser/locales/l10n.toml.orig	2021-09-26 16:24:29 UTC
+++ browser/locales/l10n.toml
@@ -134,10 +134,6 @@ locales = [
     l10n = "{l}browser/extensions/fxmonitor/**"
 
 [[paths]]
-    reference = "browser/extensions/report-site-issue/locales/en-US/**"
-    l10n = "{l}browser/extensions/report-site-issue/**"
-
-[[paths]]
     reference = "services/sync/locales/en-US/**"
     l10n = "{l}services/sync/**"
 
