PORTNAME=	glibc
PORTVERSION=	2.17
DISTVERSIONSUFFIX=	-317.el7
CATEGORIES=	devel linux

MAINTAINER=	emulation@FreeBSD.org
COMMENT=	GConf is a process-transparent configuration database API used to store user preferences (CentOS ${LINUX_DIST_VER})

USES=		linux:c7
USE_LDCONFIG=	yes
USE_LINUX_RPM=	yes

OPTIONS_DEFINE=	DOCS

.include <bsd.port.mk>
