# $FreeBSD$

PORTNAME=	libcanberra
PORTVERSION=	0.30
DISTVERSIONSUFFIX=	-9.el7
CATEGORIES=	devel linux

MAINTAINER=	emulation@FreeBSD.org
COMMENT=	A small and lightweight implementation of the XDG Sound Theme Specification (CentOS ${LINUX_DIST_VER})

USES=		linux:c7
USE_LDCONFIG=	yes
USE_LINUX_RPM=	yes

OPTIONS_DEFINE=	DOCS

.include <bsd.port.mk>
