PORTNAME=	edb-debugger
DISTVERSION=	1.3.0
CATEGORIES=	devel

MAINTAINER=	maintainer@maintainer.com
COMMENT=	edb is a cross-platform AArch32,x86,x86-64 debugger

LICENSE=	GPLv2

USES=		cmake:noninja gmake

USE_GCC=	yes
USE_GITHUB=	yes
GH_ACCOUNT=	eteran
GH_PROJECT=	edb-debugger
GH_TAGNAME=	db2bf3
GH_TUPLE=	10110111:gdtoa-desktop:8d6714f7:edbdebugger/lib/gdtoa-desktop/ \
		eteran:qhexview:7cb67c4a:edbdebugger/src/qhexview/

do-build:

do-install:

.include <bsd.port.mk>
