PORTNAME=	KTX-Software
DISTVERSIONPREFIX=v
DISTVERSION=	4.3.2
CATEGORIES=	devel

MAINTAINER=	maxfx@hades
COMMENT=	KTX (Khronos Texture) Library and Tools

LICENSE=	APACHE20
LICENSE_FILE=	${WRKSRC}/LICENSE.md

BUILD_DEPENDS=	bash:shells/bash

USES=		cmake

USE_GITHUB=	yes
GH_ACCOUNT=	KhronosGroup
GH_PROJECT=	KTX-Software

.include <bsd.port.mk>
