PORTNAME=	tracy
DISTVERSIONPREFIX=      v
DISTVERSION=	0.10
CATEGORIES=	devel

MAINTAINER=	freebsd@sysctl.cz
COMMENT=	Frame profiler 
WWW=		https://tracy.nereid.pl/

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=           cmake compiler:c11 localbase:ldflags

USE_GITHUB=     yes
GH_ACCOUNT=     wolfpld
GH_PROJECT=     tracy

.include <bsd.port.mk>
