--- cargo-crates/system_shutdown-4.0.1/Cargo.toml.orig	2025-03-29 13:02:32 UTC
+++ cargo-crates/system_shutdown-4.0.1/Cargo.toml
@@ -35,6 +35,9 @@ version = "3.7.0"
 [target."cfg(target_os = \"linux\")".dependencies.zbus]
 version = "3.7.0"
 
+[target."cfg(target_os = \"freebsd\")".dependencies.zbus]
+version = "3.7.0"
+
 [target."cfg(target_os = \"windows\")".dependencies.windows]
 version = "0.44.0"
 features = [
