--- libs/enigo/Cargo.toml.orig	2024-05-29 04:24:33 UTC
+++ libs/enigo/Cargo.toml
@@ -22,8 +22,8 @@ appveyor = { repository = "pythoneer/enigo-85xiy" }
 serde = { version = "1.0", optional = true }
 serde_derive = { version = "1.0", optional = true }
 log = "0.4"
-rdev = { git = "https://github.com/fufesou/rdev" }
-tfc = { git = "https://github.com/fufesou/The-Fat-Controller" }
+rdev = { git = "https://github.com/MartinFx/rdev" }
+tfc = { git = "https://github.com/Martinfx/The-Fat-Controller" }
 hbb_common = { path = "../hbb_common" }
 
 [features]
