--- cargo-crates/muda-0.11.4/Cargo.toml.orig	2024-06-07 12:09:06 UTC
+++ cargo-crates/muda-0.11.4/Cargo.toml
@@ -58,10 +58,10 @@ default = ["libxdo"]
 libxdo = ["dep:libxdo"]
 serde = ["dep:serde"]
 
-[target."cfg(target_os = \"linux\")".dependencies.gtk]
+[target."cfg(target_os = \"freebsd\")".dependencies.gtk]
 version = "0.18"
 
-[target."cfg(target_os = \"linux\")".dependencies.libxdo]
+[target."cfg(target_os = \"freebsd\")".dependencies.libxdo]
 version = "0.6.0"
 optional = true
 
