--- Cargo.toml.orig
+++ Cargo.toml
@@ -26,6 +26,7 @@
 use_rubato = ["rubato"]
 use_dasp = ["dasp"]
 flutter = ["flutter_rust_bridge"]
+egui = ["dep:eframe"]
 default = ["use_dasp"]
 hwcodec = ["scrap/hwcodec"]
 vram = ["scrap/vram"]
@@ -186,11 +187,11 @@
 
 [target.'cfg(any(target_os = "linux", target_os = "freebsd"))'.dependencies]
 libxdo-sys = "0.11"
+eframe = { version = "0.31", default-features = false, features = ["glow", "x11", "wayland", "default_fonts"], optional = true }
 psimple = { package = "libpulse-simple-binding", version = "2.27" }
 pulse = { package = "libpulse-binding", version = "2.27" }
 rust-pulsectl = { git = "https://github.com/rustdesk-org/pulsectl" }
 async-process = "1.7"
-evdev = { git="https://github.com/rustdesk-org/evdev" }
 dbus = "0.9"
 dbus-crossroads = "0.5"
 x11-clipboard = {git="https://github.com/clslaid/x11-clipboard", branch = "feat/store-batch", optional = true}
@@ -206,6 +207,9 @@
 [target.'cfg(any(any(target_os = "linux", target_os = "freebsd"), target_os = "android"))'.dependencies]
 openssl = { version = "0.10", features = ["vendored"] }
 
+[target.'cfg(target_os = "linux")'.dependencies]
+evdev = { git="https://github.com/rustdesk-org/evdev" }
+
 [target.'cfg(target_os = "android")'.dependencies]
 android_logger = "0.13"
 jni = "0.21"
