--- cargo-crates/muda-0.13.5/Cargo.toml.orig	2025-03-29 21:18:56 UTC
+++ cargo-crates/muda-0.13.5/Cargo.toml
@@ -64,10 +64,10 @@ serde = [
     "dpi/serde",
 ]
 
-[target."cfg(target_os = \"linux\")".dependencies.gtk]
+[target."cfg(target_os = \"freebsd\")".dependencies.gtk]
 version = "0.18"
 
-[target."cfg(target_os = \"linux\")".dependencies.libxdo]
+[target."cfg(target_os = \"freebsd\")".dependencies.libxdo]
 version = "0.6.0"
 optional = true
 
