--- libs/clipboard/Cargo.toml.orig	2024-06-07 07:55:21 UTC
+++ libs/clipboard/Cargo.toml
@@ -32,7 +32,7 @@ serde_derive = "1.0"
 hbb_common = { path = "../hbb_common" }
 parking_lot = {version = "0.12"}
 
-[target.'cfg(any(target_os = "linux", target_os = "macos"))'.dependencies]
+[target.'cfg(any(target_os = "freebsd", target_os = "macos"))'.dependencies]
 rand = {version = "0.8", optional = true}
 fuser = {version = "0.13", optional = true}
 libc = {version = "0.2", optional = true}
@@ -40,7 +40,7 @@ dashmap = {version ="5.5", optional = true}
 utf16string = {version = "0.2", optional = true}
 once_cell = {version = "1.18", optional = true}
 
-[target.'cfg(target_os = "linux")'.dependencies]
+[target.'cfg(target_os = "freebsd")'.dependencies]
 percent-encoding = {version  ="2.3", optional = true}
 x11-clipboard = {git="https://github.com/clslaid/x11-clipboard", branch = "feat/store-batch", optional = true}
 x11rb =  {version = "0.12", features = ["all-extensions"], optional = true}
