PORTNAME=	libdatovka
#DISTVERSIONSUFFIX=v
DISTVERSION=	0.2.1
CATEGORIES=	devel
MASTER_SITES=	https://secure.nic.cz/files/datove_schranky/libdatovka/

MAINTAINER=	freebsd@sysctl.cz
COMMENT=	library for program datovka

LICENSE=	LGPL3
LICENSE_FILE=	${WRKSRC}/COPYING

USES=           autoreconf gmake tar:xz
GNU_CONFIGURE=  yes
#CONFIGURE_ARGS+= 

.include <bsd.port.mk>
