PORTNAME=	rustdesk
DISTVERSION=	1.2.4
CATEGORIES=	deskutils

MAINTAINER=	freebsd@sysctl.cz
COMMENT=	Yet another remote desktop software, written in Rust. 

LICENSE=	AGPLv3
#LICENSE_FILE=	${WRKSRC}/LICENSE

BUILD_DEPENDS=  cargo-cbuild:devel/cargo-c

USES=           cargo
USE_GITHUB=     yes
GH_ACCOUNT=     rustdesk
GH_PROJECT=     rustdesk

.include <bsd.port.mk>
