--- src/xenia/app/emulator_window.cc.orig	2025-03-06 15:39:05 UTC
+++ src/xenia/app/emulator_window.cc
@@ -40,8 +40,10 @@
 #include "xenia/ui/ui_event.h"
 #include "xenia/ui/virtual_key.h"
 
-// Autogenerated by `xb premake`.
-#include "build/version.h"
+#define XE_BUILD_BRANCH "main"
+#define XE_BUILD_COMMIT_SHORT "3d30b2e"
+#define XE_BUILD_COMMIT "3d30b2eec3ab1f83140b09745bee881fb5d5dde2"
+#define XE_BUILD_DATE "20250306"
 
 DECLARE_bool(debug);
 
