PORTNAME=	cmark-gfm
DISTVERSION=	0.29.0.gfm.13
CATEGORIES=	textproc

MAINTAINER=	freebsd@sysctl.cz
COMMENT=	CommonMark parsing and rendering \
		library and program in C.
WWW=		https://github.com/github/cmark-gfm

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/COPYING

USES=		cmake pathfix

USE_GITHUB=	yes
GH_ACCOUNT=	github



.include <bsd.port.mk>
