PORTNAME=	cmake-build-extension
DISTVERSION=	0.6.1
CATEGORIES=	devel python
MASTER_SITES=	PYPI
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	cmake_build_extension-${DISTVERSION}

MAINTAINER=	freebsd@sysctl.cz
COMMENT=	This project aims to simplify the integration of C++ \
		projects based on CMake with Python packaging tools.
WWW=		https://pypi.org/project/cmake-build-extension/

LICENSE=	MIT
NO_ARCH=	yes
USES=		python
USE_PYTHON=	autoplist distutils flavors

.include <bsd.port.mk>
