PORTNAME=	spirv-reflect
DISTVERSIONPREFIX=vulkan-sdk-
DISTVERSION=	1.3.283.0
CATEGORIES=	devel

MAINTAINER=	freebsd@sysctl.cz
COMMENT=	SPIRV-Reflect is a lightweight library that provides a C/C++ reflection API.
WWW=		https://github.com/KhronosGroup/spirv-reflect

LICENSE=	APACHE20
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		cmake

USE_GITHUB=	yes
GH_ACCOUNT=	KhronosGroup
GH_PROJECT=	SPIRV-Reflect
GH_TUPLE=	google:googletest:e2239ee:googletest/third_party/googletest

.include <bsd.port.mk>
