--- cmake/BuildPCRE2.cmake.orig	2023-09-22 06:15:26 UTC
+++ cmake/BuildPCRE2.cmake
@@ -9,7 +9,7 @@ ExternalProject_Add(pcre2 SOURCE_DIR ${CMAKE_SOURCE_DI
   CMAKE_ARGS -DCMAKE_C_FLAGS=-fPIC -DBUILD_SHARED_LIBS=N -DPCRE2_BUILD_PCRE2GREP=N -DPCRE2_BUILD_TESTS=N
   -DPCRE2_SUPPORT_JIT=Y -DPCRE2_HEAP_LIMIT=1000000 -DPCRE2_MATCH_LIMIT=500000
   BINARY_DIR ${CMAKE_BINARY_DIR}/pcre2/
-  BUILD_COMMAND make
+  BUILD_COMMAND gmake
   INSTALL_COMMAND ""
   LOG_DOWNLOAD 1
   LOG_UPDATE 1
