--- cmake/BuildPCRE2.cmake.orig	2022-10-08 18:17:57 UTC
+++ cmake/BuildPCRE2.cmake
@@ -8,7 +8,7 @@
 ExternalProject_Add(pcre2 SOURCE_DIR ${CMAKE_SOURCE_DIR}/pcre2/
   CMAKE_ARGS -DCMAKE_C_FLAGS=-fPIC -DBUILD_SHARED_LIBS=N -DPCRE2_BUILD_PCRE2GREP=N  -DPCRE2_BUILD_TESTS=N -DPCRE2_SUPPORT_JIT=Y
   BINARY_DIR ${CMAKE_BINARY_DIR}/pcre2/
-  BUILD_COMMAND make
+  BUILD_COMMAND gmake
   INSTALL_COMMAND ""
   LOG_DOWNLOAD 1
   LOG_UPDATE 1
