--- src/brave/browser/misc_metrics/BUILD.gn.orig	2026-06-01 00:00:00 UTC
+++ src/brave/browser/misc_metrics/BUILD.gn
@@ -71,6 +71,7 @@
     "//content/public/browser",
     "//mojo/public/cpp/bindings",
     "//services/media_session/public/mojom",
+    "//third_party/widevine/cdm:buildflags",
     "//ui/base",
     "//ui/gfx/geometry",
   ]
