--- src/cmake/friction-common.cmake.orig	2025-08-06 11:39:26 UTC
+++ src/cmake/friction-common.cmake
@@ -29,7 +29,7 @@ option(BUILD_ENGINE "Build Engine" ON)
 option(MAC_DEPLOY "Mac Deploy" OFF)
 option(WIN_DEPLOY "Windows Deploy" OFF)
 option(BUILD_ENGINE "Build Engine" ON)
-set(ENGINE_LIB_PATH "/mnt/skia" CACHE STRING "Path to prebuilt skia library")
+#set(ENGINE_LIB_PATH "/mnt/skia" CACHE STRING "Path to prebuilt skia library")
 
 if(${LINUX_DEPLOY})
     add_definitions(-DLINUX_DEPLOY)
@@ -106,12 +106,12 @@ else()
     if(APPLE)
         set(SKIA_LIBRARIES skia)
     else()
-        set(SKIA_LIBRARIES skia.friction)
+        set(SKIA_LIBRARIES skia)
     endif()
     if(UNIX AND NOT APPLE)
         pkg_check_modules(UNWIND REQUIRED libunwind)
         set(GPERF_INCLUDE_DIRS ${CMAKE_CURRENT_BINARY_DIR}/../gperftools ${UNWIND_INCLUDE_DIRS})
-        set(GPERF_LIBRARIES tcmalloc_static ${UNWIND_LIBRARIES})
+#        set(GPERF_LIBRARIES tcmalloc_static ${UNWIND_LIBRARIES})
     endif()
     if(${BUILD_ENGINE})
         set(SKIA_LIBRARIES_DIRS ${CMAKE_CURRENT_BINARY_DIR}/../engine/skia)
