
PORTNAME=	reaver
PORTVERSION=	1.6.4
CATEGORIES=	net
MASTER_SITES=	https://github.com/t6x/reaver-wps-fork-t6x/archive/
DISTNAME=	v${PORTVERSION}

MAINTAINER=	email
COMMENT=	Reaver brute force attack against Wifi Protected Setup (WPS) registrar PINs.

LICENSE=	GPLv2

GNU_CONFIGURE=	yes
USES=		autoreconf gmake

WRKSRC=		${WRKDIR}/reaver-wps-fork-t6x-${PORTVERSION}/src

.include <bsd.port.mk>
