# $FreeBSD$

PORTNAME=	double-conversion
DISTVERSIONPREFIX=	v
DISTVERSION=	3.1.5
CATEGORIES=	devel

MAINTAINER=	freebsd@sysctl.cz
COMMENT=	Provides binary-decimal and decimal-binary routines for IEEE doubles.

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		cmake

USE_GITHUB=	yes
GH_ACCOUNT=	google

CMAKE_ON=	BUILD_TESTING

.include <bsd.port.mk>
