PORTNAME=	keystone
DISTVERSION=	0.9.2
CATEGORIES=	devel

MAINTAINER=	freebsd@sysctl.cz
COMMENT=	Keystone assembler framework.
WWW=		https://www.keystone-engine.org/

LICENSE=	GPLv2
LICENSE_FILE=	${WRKSRC}/COPYING

USES=		cmake compiler:c++23-lang

USE_GITHUB=	yes
GH_ACCOUNT=	keystone-engine
GH_PROJECT=	keystone
GH_TAGNAME=	fb92f32

.include <bsd.port.mk>
