PORTNAME=       portsmf
DISTVERSION=    239
CATEGORIES=     multimedia
MASTER_SITES=   https://codeberg.org/tenacityteam/${PORTNAME}/archive/${DISTVERSIONFULL}${EXTRACT_SUFX}?dummy=/

MAINTAINER=     root@hades
COMMENT=        Portsmf is "Port Standard MIDI File". 
WWW=            https://codeberg.org/tenacityteam/portsmf

LICENSE_NAME=	unknown
LICENSE_PERMS=	auto-accept
LICENSE_FILE=	${WRKSRC}/license.txt

USES=		cmake

WRKSRC=		${WRKDIR}/${PORTNAME}

.include <bsd.port.mk>
